### ISSUE TITLE
任务12：更新arm源，测试24.03 arm架构下 ROS2 Humble相关功能，看之前存在的问题是否已经解决（7月12号前完成，可多人接此任务）

### ISSUE THREAD

**Issue by jiuyewxy** [jiuyewxy/weloveinterns#14]
# 说明
- 新源：https://eulermaker.compass-ci.openeuler.openatom.cn/api/ems1/repositories/ROS-SIG-Multi-Version_ros-humble_openEuler-24.03-LTS-TEST4/openEuler%3A24.03-LTS/aarch64/
- 关联欧拉社区issue：https://gitee.com/openeuler/ros/issues/IA81ZG?from=project-issue
- 上传新的测试报告，同时更新欧拉ros仓库中的测试报告：https://gitee.com/openeuler/ros/tree/master/user_doc/ROS-humble-oerv24.03-arm

**Comment by ArthurWANGZHE** [comment]
accept

**Comment by ArthurWANGZHE** [comment]
报告链接：https://github.com/ArthurWANGZHE/plct/blob/master/Task12/ARM.md
社区pr：https://gitee.com/openeuler/ros/commit/43863f07a73740a3a8e3506c77df8a7cebc3aceb

**Comment by jiuyewxy** [comment]
本次测试任务已完成，关闭issue
