### ISSUE TITLE
任务13：编写欧拉社区贡献者指南文档——01注册gitee签署 openEuler 开源社区的 CLA（7月15号之前，可与其他任务同时进行）

### ISSUE THREAD

**Issue by jiuyewxy** [jiuyewxy/weloveinterns#15]
- 将文档提交到 https://gitee.com/openeuler/ros  的document文件夹下
- 文件名用英文，md文档
- 内容越详细越好，重点说明下需要注意的点
- 同时修改仓库的readme，贴上文档链接：注册gitee签署 openEuler 开源社区的 CLA
![1720496207591](https://github.com/jiuyewxy/weloveinterns/assets/48117146/c9f24ff8-5c1c-4a5e-bd86-bdab67590500)

### 注册gitee
可直接贴参考链接：https://gitee.com/help
https://gitee.com/openeuler/community/blob/master/zh/contributors/Gitee-workflow.md

**着重点名如何正确设置git和gitee才能保证正确签署CLA**

### 签署CLA
说明下签署个人还是企业
参考：https://www.openeuler.org/zh/blog/2022-11-25-cla/CLA%E7%AD%BE%E7%BD%B2%E6%B5%81%E7%A8%8B.html

其他参考：https://gitee.com/openeuler/RISC-V/blob/master/doc/tutorials/account-oE-CLA.md

**Comment by ArthurWANGZHE** [comment]
accept

**Comment by jiuyewxy** [comment]
https://gitee.com/openeuler/ros/pulls/13 已完成关闭issue
