### ISSUE TITLE
任务14：梳理24.03 X86架构下安装失败的ROS Humble相关包，整理成表格（7-25号之前，可与其他任务同时接）

### ISSUE THREAD

**Issue by jiuyewxy** [jiuyewxy/weloveinterns#16]
安装ROS时，如果不加--skip-broken参数，可看到46个包的安装错误信息
```
dnf install ros-humble-*
```
![c3909cff678ff67f5fad09fb2749c43](https://github.com/user-attachments/assets/200ed3fc-acb1-4e41-895e-d8ef77e334e6)

可以看到大部分原因都是依赖问题。

需要将安装失败的包名、错误信息、在gitee上的仓库名等汇总成表格，后续再安排新的任务解决这些问题

- 欧拉sigROS下所有的软件包汇总：https://gitee.com/openeuler/community/tree/master/sig/sig-ROS/src-openeuler

**Comment by ArthurWANGZHE** [comment]
accept

**Comment by ArthurWANGZHE** [comment]
https://github.com/ArthurWANGZHE/plct/blob/master/Task14/broken_packages.md

**Comment by jiuyewxy** [comment]
该任务结束，后续采用具体包具体任务的方式发布任务
